name: Hardware manufacturing package

on:
  workflow_dispatch:
  push:
    tags:
      - "hw-v*"
      - "v*"

permissions:
  contents: write

jobs:
  manufacturing:
    uses: Ploos-AS/hardware-ci/.github/workflows/manufacturing.yml@v1
    with:
      publish_release: true
